import type { Metadata, Viewport } from "next";
import {
  APP_URL,
  AUTHOR_NAME,
  TWITTER_HANDLE,
} from "@/lib/site-config";

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: {
    default: "Samir Shaikh - AI Backend Engineer | AI SDE | Agentic AI Engineer | Forward Deployed Engineer",
    template: "%s | Samir Shaikh",
  },
  description:
    "Samir Shaikh is an AI Backend Engineer and AI SDE building production RAG pipelines, autonomous agentic AI workflows, and scalable distributed systems. Exploring Forward Deployed Engineer (FDE) roles combining backend depth with direct customer ownership.",
  keywords: [
    "Samir Shaikh",
    "Samir Shaikh Portfolio",
    "AI Backend Engineer",
    "AI Engineer",
    "AI SDE",
    "SDE",
    "Software Development Engineer",
    "Agentic AI",
    "Agentic AI Engineer",
    "AI Agents",
    "AI Agent Development",
    "Autonomous AI",
    "Multi-Agent Systems",
    "AI Orchestration",
    "Tool-Using AI",
    "Forward Deployed Engineer",
    "Applied AI Engineer",
    "Customer-Facing Engineer",
    "Backend Engineer AI",
    "LLM Engineer",
    "RAG Engineer",
    "Retrieval Augmented Generation",
    "Vector Search",
    "Vector Database",
    "pgvector",
    "Semantic Search",
    "Vercel AI SDK",
    "Google Gemini API",
    "OpenAI API",
    "Prompt Engineering",
    "AI Chatbot Development",
    "LLM Integration",
    "Embeddings",
    "Node.js Developer",
    "Backend Developer",
    "Backend Developer India",
    "Node.js Backend Developer",
    "Express.js",
    "NestJS",
    "GraphQL",
    "REST API",
    "Microservices",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Firebase",
    "Drizzle ORM",
    "Sequelize",
    "BullMQ",
    "Apache Kafka",
    "Docker",
    "TypeScript",
    "JavaScript",
    "Full Stack Developer",
    "Next.js",
    "React",
    "Serwist",
    "Sharp",
    "Nodemailer",
    "TipTap",
    "Web Developer",
    "Open to Remote",
    "Logicwind",
    "Xira Infotech",
    "Full Stack Engineer",
    "Uka Tarsadia University",
    "Gujarat Developer",
    "API Integration",
    "JWT Authentication",
    "Socket.io",
    "OpenTelemetry",
    "Prometheus",
    "Grafana",
    "CI/CD",
    "GitHub Actions",
    "System Design",
    "Distributed Systems",
    "Event Driven Architecture",
    "Message Queues",
    "Scalable Backend Systems",
    "High Performance APIs",
    "Backend Developer Portfolio",
    "Software Engineer Portfolio",
    "Node.js Portfolio",
    "Next.js Portfolio",
    "MERN Stack Developer",
    "TypeScript Developer",
    "Node.js API Developer",
    "GraphQL Developer",
    "REST API Developer",
    "PostgreSQL Developer",
    "MongoDB Developer",
    "Express.js Developer",
    "NestJS Developer",
    "React Developer",
    "Hire Node.js Developer",
    "Hire Backend Developer",
    "Freelance Backend Developer",
    "Freelance Node.js Developer",
    "Remote Backend Developer",
    "Backend Developer Open to Work",
    "Backend Developer with TypeScript",
    "Contract Backend Developer",
    "API Development Services",
    "Custom Web Development",
    "Node.js Consultant",
    "AI Node.js Developer",
    "AI Backend Developer",
    "AI Backend Developer India",
    "AI Node.js Backend Developer",
    "AI Full Stack Developer",
    "AI Full Stack Engineer",
    "AI Web Developer",
    "AI Software Development Engineer",
    "AI MERN Stack Developer",
    "AI TypeScript Developer",
    "AI Node.js API Developer",
    "AI GraphQL Developer",
    "AI REST API Developer",
    "AI PostgreSQL Developer",
    "AI MongoDB Developer",
    "AI Express.js Developer",
    "AI NestJS Developer",
    "AI React Developer",
    "AI Node.js Consultant",
  ],
  authors: [{ name: AUTHOR_NAME, url: APP_URL }],
  creator: AUTHOR_NAME,
  openGraph: {
    title: "Samir Shaikh - AI Backend Engineer | AI SDE | Agentic AI Engineer | Forward Deployed Engineer",
    description:
      "Samir Shaikh is an AI Backend Engineer and AI SDE building production RAG pipelines, autonomous agentic AI workflows, and scalable distributed systems. Exploring Forward Deployed Engineer roles.",
    url: APP_URL,
    siteName: "Samir Shaikh Portfolio",
    images: [
      {
        url: "/Filled_Logo.png",
        width: 1200,
        height: 630,
        alt: "Samir Shaikh - AI Backend Engineer | AI SDE | Agentic AI Engineer | Forward Deployed Engineer",
      },
    ],
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Samir Shaikh - AI Backend Engineer | AI SDE | Agentic AI Engineer | Forward Deployed Engineer",
    description:
      "AI Backend Engineer and AI SDE building production RAG pipelines, autonomous agentic AI workflows, and scalable distributed systems.",
    images: ["/Filled_Logo.png"],
    creator: TWITTER_HANDLE,
  },
  verification: {
    google: "H6Pq0eI_0M2sSwSWyHpuCbS7ufcyBMaw_r2k7VCv9Ok",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  alternates: {
    canonical: APP_URL,
  },
};

export const viewport: Viewport = {
  themeColor: "#000000",
};
